### ISSUE TITLE
multiple voice options

### ISSUE THREAD

**Issue by antoniocasino** [Kais3rP/react-text2speech#13]
Would be great if you add a female/young/old voice option in the text reader.

**Comment by Kais3rP** [comment]
Hi Antonio, that's not an easy task since the set of voices is browser dependant and changes from mobile to desktop. 
Plus the voice instance does not hold such info in many cases.
These are the properties held by the instance:
[default](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/default)
[lang](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/lang)
[localService](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/localService)
[name](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/name)
[voiceURI](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/voiceURI)

Sometimes the *voiceURI* holds the female/male to distinguish the gender, but in many cases it doesn't so it would not be a reliable feature.
Young/old would be even harder to implement.
